feat: migration from plaintext to encrypted data
cloudfoundry-incubator/cloud-service-broker pull request #294
Opened 2021-09-06 22:43 UTC by blgm

If a database has been using plaintext, when a new primary password is specified, the database will be re-encrypted on the next startup.

[#179355268](https://www.pivotaltracker.com/story/show/179355268)

2021-09-07 11:18 UTC, FelisiaM requested changes

2021-09-07 11:18 UTC, FelisiaM commented on internal/encryption/dbrotator/dbrorator.go
> +	return nil
At the end of re-encryption we still have not updated the new password to be "primary" in the DB. This means that when the app restarts it will attempt to re-encrypt again even though nothing will have changed.

2021-09-07 11:18 UTC, FelisiaM commented on integrationtest/database_encryption_test.go
> +			brokerSession = startBroker(true, encryptionPasswords)
I think there is one more case that this test should check. If you restart the broker again with the same password configuration it should be able to access the same data and delete instances/bindings. This would prove that we are keeping track of something relating to the password in the DB.

2021-09-07 11:22 UTC, FelisiaM commented on internal/encryption/dbrotator/dbrorator_test.go
> +package dbrotator_test
same issue with typo in the file name

2021-09-07 11:27 UTC, FelisiaM commented on internal/encryption/passwordcombiner/combinedpasswords.go
> +	parsedPrimary bool
I wonder if there is a better name for `parsedPrimary` since "parsing" is not really the important concept here. It's more "configured".  What do you think?

2021-09-08 08:40 UTC, FelisiaM approved these changes

2021-09-08 08:46 UTC, blgm commented on internal/encryption/dbrotator/dbrorator.go
> +	return nil
Added.

2021-09-08 08:46 UTC, blgm commented on integrationtest/database_encryption_test.go
> +			brokerSession = startBroker(true, encryptionPasswords)
Added.

2021-09-08 08:48 UTC, merged