feat: Decrypt DB when turning encryption off
cloudfoundry-incubator/cloud-service-broker pull request #296
Opened 2021-09-09 12:11 UTC by FelisiaM

[#179355269](https://www.pivotaltracker.com/story/show/179355269)

2021-09-09 14:51 UTC, blgm requested changes

2021-09-09 14:51 UTC, blgm commented on integrationtest/database_encryption_test.go
> +			Expect(persistedServiceBindingTerraformWorkspace(serviceInstanceGUID, serviceBindingGUID)).NotTo(bePlaintextBindingTerraformState)
Should use `haveAnyPlaintextBindingTerraformState` matcher

2021-09-09 14:51 UTC, blgm commented on integrationtest/database_encryption_test.go
> +			Expect(persistedServiceInstanceTerraformWorkspace(serviceInstanceGUID)).NotTo(haveAnyPlaintextServiceTerraformState)
Should use `haveAnyPlaintextServiceTerraformState` matcher

2021-09-09 14:51 UTC, blgm commented on integrationtest/database_encryption_test.go
> +			Expect(persistedServiceBindingDetails(serviceInstanceGUID)).To(bePlaintextBindingDetails)
Should use `bePlaintextBindingTerraformState` matcher

2021-09-09 14:51 UTC, blgm commented on integrationtest/database_encryption_test.go
> +			encryptionPasswords = `[{"primary":false,"label":"my-password","password":{"secret":"supersecretcoolpassword"}}]`
Would it be a better test to remove the password completely?

2021-09-09 14:51 UTC, blgm commented on internal/encryption/parse_configuration.go
> +	switch {
I think this switch should be split, so that the guard clauses are at the top of the function:
```go
switch {
case enabled && !parsedPrimaryOK:
  return Configuration{}, errors.New("encryption is enabled but no primary password is set")
case !enabled && parsedPrimaryOK:
  return Configuration{}, errors.New("encryption is disabled but a primary password is set")
}
```

And the success branches should have duplication removed:
```go
result := Configuration{
  ConfiguredPrimaryLabel: labelName(parsedPrimary.Label),
  StoredPrimaryLabel: labelName(storedPrimary.Label),
  Changed: changed,
  RotationEncryptor: rotationEncyptor,
}

if !enabled && !parsedPrimaryOK {
  result.Encryptor = noopencryptor.New()
} else {
  result.Encryptor = parsedPrimary.Encryptor
}

return result, nil
```

2021-09-09 14:51 UTC, blgm commented on internal/encryption/update_password_metadata.go
> +		if !(configuredPrimaryLabel == "" || configuredPrimaryLabel == "none") {
The `"none"` text should really only be a UI external. We should display it to a user, but not use it for internal processing. Maybe we should move the conversion to the `serve()` function.

2021-09-09 14:51 UTC, blgm commented on internal/encryption/compoundencryptor/compoundencryptor.go
> -	for _, decryptor := range append([]Encryptor{c.primary}, c.secondaries...) {
I think change introduces a bug. In cases where the database re-encryption fails without completing, when the CSB restarts it will try to re-encrypt the database again. It therefore needs to be able to decrypt with the primary otherwise it will not be able to recover.

2021-09-09 15:50 UTC, FelisiaM commented on internal/encryption/update_password_metadata.go
> +		if !(configuredPrimaryLabel == "" || configuredPrimaryLabel == "none") {
Good catch - I put it as a temp solution and meant to change that before submitting the PR but forgot.

2021-09-10 10:45 UTC, FelisiaM commented on internal/encryption/compoundencryptor/compoundencryptor.go
> -	for _, decryptor := range append([]Encryptor{c.primary}, c.secondaries...) {
I added a [test](https://github.com/cloudfoundry-incubator/cloud-service-broker/pull/296/files#diff-67301087574d31ce4500119d0c090bdf29419a445babc3be72495823f7241ec2R180) for this use case and I think there is no bug.  In cases where the database re-encryption fails without completing, the intended new key would still be stored in the DB, just not labeled as "primary". This means it will be part of the combined passwords that are returned from [`passwordcombiner.CombineWithStoredMetadata`](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/4ac02be2930f18349350da986d2ad4f2bb997385/internal/encryption/parse_configuration.go#L23). Since we add the encryptors from the combined passwords as decryptors for rotation the right decryptor will be available.

2021-09-10 10:57 UTC, blgm commented on internal/encryption/compoundencryptor/compoundencryptor.go
> -	for _, decryptor := range append([]Encryptor{c.primary}, c.secondaries...) {
Ok. A test is definitely the right way to resolve this.

2021-09-10 10:59 UTC, blgm approved these changes

2021-09-10 11:12 UTC, merged