Use blob fields to store encrypted data
cloudfoundry-incubator/cloud-service-broker pull request #305
Opened 2021-09-23 15:41 UTC by FelisiaM

[#179479743](https://www.pivotaltracker.com/story/show/179479743)

2021-09-27 11:26 UTC, blgm requested changes

2021-09-27 11:26 UTC, blgm commented on db_service/dao_test.go
> +	instance.OtherDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x65,
This is hard to reason about. I'd much prefer:
```go
instance.OtherDetails = []byte("whatever it actually says")
```

2021-09-27 11:26 UTC, blgm commented on db_service/dao_test.go
> +	instance.OtherDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x65,
As before

2021-09-27 11:26 UTC, blgm commented on db_service/dao_test.go
> +	instance.RequestDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x6
As before

2021-09-27 11:26 UTC, blgm commented on db_service/dao_test.go
> +	instance.Workspace = []byte{0x7b, 0x7d}
As before

2021-09-27 11:26 UTC, blgm commented on db_service/models/db.go
> +type ProvisionRequestDetails ProvisionRequestDetailsV3
What happened to V2?

2021-09-27 11:26 UTC, blgm commented on db_service/models/historical_db.go
> +type ProvisionRequestDetailsV3 struct {
What happened to V2?

2021-09-27 11:26 UTC, blgm commented on db_service/models/historical_db.go
> +// TableName returns a consistent table name (`terraform_deployments`) for
In general, I'd rather not duplicate the return value in the comment as it just leaves the problem for someone to trip over in the future. If the comment reads:
```go
// TableName returns a consistent table name for
// gorm so multiple structs from different versions of the database all operate
// on the same table.
```
Then no-one can get it wrong again

2021-09-27 11:26 UTC, blgm commented on internal/encryption/gcmencryptor/gcmencryptor_test.go
> +		//It("encodes in b64", func() {
Can we remove this please?

2021-09-27 11:26 UTC, blgm commented on internal/encryption/parse_configuration_test.go
> +					Canary:  []byte{73, 191, 136, 182, 178, 54, 18, 6, 195, 170, 245, 114, 29, 34, 193, 95, 213, 107, 30, 23, 38, 202, 37, 226, 118, 10, 247, 73, 117, 96, 27, 238, 210, 27, 46, 196, 161, 100, 254, 5
I'd prefer to see `[]byte("some readable data")` as even when that data is random, you can tell that. Whereas when it's a list of numbers it leaves you curious as to what it actually says. Because not all bytes are printable, it might not be possible to do that, but in that situation I'd like to see a comment, or a variable names that gives some context so that future readers have some idea of what this data is.

2021-09-27 11:26 UTC, blgm commented on internal/encryption/parse_configuration_test.go
> +					Canary:  []byte{130, 100, 227, 172, 226, 139, 19, 69, 68, 165, 60, 67, 132, 158, 234, 45, 52, 5, 57, 243, 5, 41, 33, 170, 30, 52, 47, 204, 3, 137, 96, 132, 16, 24, 184, 33, 241, 24, 149, 35},
As before

2021-09-27 11:26 UTC, blgm commented on internal/encryption/parse_configuration_test.go
> +				Expect(config.Encryptor.Decrypt([]byte{59, 21, 133, 191, 122, 237, 117, 45, 137, 121, 21, 128, 28, 100, 131, 163, 91, 252, 73, 20, 74, 104, 237, 20, 103, 53, 207, 52, 154, 189, 66})).To(Equal([]b
As before

2021-09-27 11:26 UTC, blgm commented on internal/encryption/parse_configuration_test.go
> +				encryptedCanary = []byte{38, 164, 195, 221, 176, 254, 121, 38, 51, 178, 60, 148, 18, 102, 146, 111, 95, 42, 233, 14, 42, 144, 50, 24, 159, 21, 162, 43, 230, 65, 211, 93, 219, 85, 11, 27, 77, 78,
As before

2021-09-27 11:26 UTC, blgm commented on internal/encryption/parse_configuration_test.go
> +					encryptedCanary = []byte{190, 41, 181, 143, 95, 250, 158, 190, 25, 39, 45, 52, 26, 2, 67, 182, 4, 118, 144, 6, 30, 67, 150, 143, 20, 242, 15, 133, 160, 108, 38, 57, 102, 39, 119, 25, 40, 246, 75
As before

2021-09-27 11:26 UTC, blgm commented on internal/encryption/passwordcombiner/combiner_test.go
> +					Canary:  []byte{250, 65, 162, 134, 203, 81, 170, 159, 176, 113, 29, 249, 223, 77, 187, 139, 97, 254, 110, 99, 177, 102, 234, 51, 47, 85, 126, 205, 110, 173, 159, 209, 234, 138, 66, 113, 117, 191
As before

2021-09-27 11:26 UTC, blgm commented on internal/encryption/passwordcombiner/combiner_test.go
> +				Canary:  []byte{74, 35, 85, 82, 16, 202, 239, 216, 209, 30, 158, 65, 28, 0, 77, 203, 96, 155, 20, 61, 16, 204, 81, 147, 22, 42, 144, 193, 95, 50, 47, 207, 156, 106, 219, 159, 90, 8, 13, 59},
As before

2021-09-28 11:33 UTC, pivotal-marcela-campo commented on db_service/dao_test.go
> +	instance.OtherDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x65,
this is generated code so can't improve it

2021-09-28 11:33 UTC, pivotal-marcela-campo commented on db_service/dao_test.go
> +	instance.Workspace = []byte{0x7b, 0x7d}
this is generated code so can't improve it

2021-09-28 11:33 UTC, pivotal-marcela-campo commented on db_service/dao_test.go
> +	instance.RequestDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x6
this is generated code so can't improve it

2021-09-28 13:35 UTC, pivotal-marcela-campo commented on db_service/dao_test.go
> +	instance.OtherDetails = []byte{0x7b, 0x22, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x3a, 0x5b, 0x22, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x2c, 0x22, 0x68, 0x65, 0x72, 0x65,
These are autogenerated tests so work to change this probably is not worth it.

2021-09-28 13:36 UTC, pivotal-marcela-campo commented on internal/encryption/parse_configuration_test.go
> +					Canary:  []byte{73, 191, 136, 182, 178, 54, 18, 6, 195, 170, 245, 114, 29, 34, 193, 95, 213, 107, 30, 23, 38, 202, 37, 226, 118, 10, 247, 73, 117, 96, 27, 238, 210, 27, 46, 196, 161, 100, 254, 5
As discussed, extracting variables so the long arrays don't mess with the readability of the text.

2021-09-28 13:43 UTC, pivotal-marcela-campo commented on db_service/models/historical_db.go
> +type ProvisionRequestDetailsV3 struct {
There is a V2 used in the migrations.

2021-09-28 14:00 UTC, merged